Import('env')
local_env = env.Clone()


local_env.AppendUnique(CPPPATH = ['../googletest/gtest-1.8.0'])
local_env.AppendUnique(CPPPATH = ['../googletest/gtest-1.8.0/include'])
local_env.AppendUnique(CPPPATH = ['gmock-1.8.0'])
local_env.AppendUnique(CPPPATH = ['gmock-1.8.0/include'])


source_files = ['gmock-1.8.0/src/gmock-all.cc']


target = 'gmock'

program = local_env.StaticLibrary(target, source_files)
env.Alias(target, '.')
